### ISSUE TITLE
Support for Generator Options

### ISSUE THREAD

**Issue by synerp** [ridafkih/schemix#11]
Hi there!

I am having trouble defining generator options when supplying an array of generators.

For example I want to use https://github.com/kimjbstar/prisma-class-generator which has an option of 'seperateRelationFields'.

This works:
```
  generator: [
    {
      name: 'client',
      provider: 'prisma-client-js',
      output: '../data-access/src/lib/@prisma',
    },
    {
      name: 'nestgraphql',
      provider: 'node node_modules/prisma-nestjs-graphql',
      output: '/mnt/wsl/global/business/prisma',
      outputFilePattern: '{name}.{type}.ts',
    },
    {
      name: 'prismaIncludesGenerator',
      provider: 'node node_modules/prisma-includes-generator',
      output: '/mnt/wsl/global/business/prisma',
      // seperateRelationFields: true, <--- Uncomment to break
    },
  ],
```

When I uncomment the extra option, I get the following error: 

```
Type '{ name: string; provider: string; seperateRelationFields: true; output: string; outputFilePattern: string; }' is not assignable to type 'string | string[] | undefined'.
  Object literal may only specify known properties, and 'name' does not exist in type 'string[]'.ts(2322)
```

Thanks for you help.

-Paul

**Comment by ridafkih** [comment]
Hey, thanks for this. I failed to take into account third-party generator options. I will add this functionality.

**Comment by ridafkih** [comment]
@synerp I've gone ahead and made a pull-request (#13) which addresses this ticket. I'll merge it in this evening, let me know if there are other datatypes I should add as permitted.
