### ISSUE TITLE
How do I create @@id([])

### ISSUE THREAD

**Issue by synerp** [ridafkih/schemix#12]
Quick question:
How do I create a composite primary key like described here?

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#id-1

Thanks

-Paul

**Comment by ridafkih** [comment]
Right now you can use `.raw("@@id([])")`, but we can add a formal method to enable this functionality.

**Comment by ridafkih** [comment]
Went ahead and addressed this in issue #14. Please give it a once-over, will have it merged this evening. :)

Thanks for raising the issues, you've made schemix more useful for everyone! 🥰
