### ISSUE TITLE
Supports more model level attributes

### ISSUE THREAD

**Issue by thwonghin** [ridafkih/schemix#15]
As the title said. My personal wishes are:
- [@@map](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#map-1)
- [@@unique](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#unique-1)
- [@@index](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#index)

**Comment by ridafkih** [comment]
Sounds good, I can start working on these. For the time being, you can use `.raw`! :)

**Comment by ridafkih** [comment]
In options.ts:82 I have the `buildCompositeId` function which looks like this...

```ts
export const buildCompositeId = (options: CompositeIDFieldOptions) => {
  const fields = `[${options.fields.join(", ")}]`;
  if (!options.map && !options.name) return `@@id(${fields})`;

  const referenceArguments: [string, string][] = [["fields", fields]];
  if (options.map) referenceArguments.push(["map", options.map]);
  if (options.name) referenceArguments.push(["name", options.name]);

  const parsedArguments: string = referenceArguments
    .map(([property, value]) => `${property}: ${value}`)
    .join(", ");

  return `@@id(${parsedArguments})`
};
```

We could abstract its functionality to work across all these attributes.

**Comment by ridafkih** [comment]
The function name probably needs some improvement anyways. :P

**Comment by zygopleural** [comment]
Would be really great to get these in as this is blocking us from moving all our models over to `schemix`. Namely we have a lot of `@@map` and `@@unique`

@ridafkih could you give an example of 👇🏼 

> For the time being, you can use .raw! :)

**Comment by zygopleural** [comment]
I didn't bother abstracting the logic for composite ID, but implemented something here: https://github.com/ridafkih/schemix/pull/23
