### ISSUE TITLE
Auto mapping the field names to snake_case

### ISSUE THREAD

**Issue by thwonghin** [ridafkih/schemix#16]
I've been trying to find a way to auto map the field names to snake case, this library has potential to do it cleanly.
I think the easiest way right now is to have a helper function to inject a `map` attribute to the field options:

```ts
import { snakeCase } from 'snake-case';

function addStringFieldMappedSnakeCase(model: PrismaModel, name: string, options: StringFieldOption) {
    model.string(name, { map: snakeCase(name), ...options });

    return model;
}
```

But then I will have to add a similar method for each different field types in order to staisify the types.
This also breaks the nice method chaining while defining the model.

Would you consider expand the API for this purpose? For example allowing users to retrieve all fields definition to edit them afterwards within the model declaration:

```ts
export default createModel((model) => {
    model
        .string('firstName')
        .string('lastName')
        .dateTime('createdAt');

    model.fields.forEach((field) => ({
        ...field,
        map: snakeCase(field.name),
    }));
});
```

**Comment by thwonghin** [comment]
Oh I figured out that I can create a function that returns the arguments to be used by the field method:
```ts
function camelCaseField(name: string, options: any) {
    return [
        name,
        {
            ...options,
            map: camelCase(name),
        },
    ]
}

model
    .string(...camelCaseField('firstName', { optiona: true })
    .dateTime(...camelCaseField('createdAt'))
```

It is a bit easier, but I still have to define it for every field.

**Comment by ridafkih** [comment]
Do we potentially want to simply allow users to provide a parameter or option and have it do this automatically for the entire schema, or on a per-field/model basis?

**Comment by thwonghin** [comment]
Schema level option will be the most convenient for this kind of purpose.
Per-field/model basis option is nice to have, but I couldn't think of a valid use-case at this moment.

**Comment by thwonghin** [comment]
I am thinking of a pattern like this:
- Add field level mixins to `PrismaModel`
    - The mixins will be run before constructing `PrismaScalarField` or `PrismaEnumField`
    - Only allow mutating the field options passed in
        - I don't think it is useful to modify the fieldName and the type, and it would make the typings awkward
- Allow passing a list of model mixins as an option when creating a schema

```ts
// types
interface PrismaModel {
    // see if we can generalize these two methods while keeping good typings
    addFieldMixin(fieldName: string, type: PrismaFieldTypeName, options: PrismaScalarField | PrismaRelationalField | PrismaEnumField): void
    addEnumFieldMixin(fieldName: string, type: string, options: PrismaEnumOptions): void
}

type ModelMixin = typeof createMixin;

interface CreateSchemaOptions {
    modelMixins: ModelMixin[]
}

// usage
function snakeCaseMixin(Mixin: PrismaModel) {
    Mixin.addFieldMixin((fieldName, type, options) => {
        options.map = snakeCase(fieldName)
    });

    Mixin.map(pluralize(snakeCase(model.name))
}


function uuidDefaultValueMixin(Mixin: PrismaModel) {
    Mixin.addFieldMixin((fieldName, type, options) => {
        if (options.default.uuid) {
            options.raw = '@database.Uuid'
        }
    });
}

function datetimeMixin(Mixin: PrismaModel) {
     Mixin
        .dateTime("createdAt", { default: { now: true } })
        .dateTime("updatedAt", { updatedAt: true });
}

createSchema({
    ...otherOptions,
    modelMixins: [
        datetimeMixin,
        uuidDefaultValueMixin,
        snakeCaseMixin,
    ]
})

```

**Comment by thwonghin** [comment]
If it is generally ok to you I can start the implementation.

**Comment by ridafkih** [comment]
@thwonghin Absolutely.

**Comment by thwonghin** [comment]
I gave up on using Prisma so I will not continue to implement this. Good luck with the project!
