### ISSUE TITLE
Shadow Database Url

### ISSUE THREAD

**Issue by darknessxk** [ridafkih/schemix#19]
I was attempting to add the Shadow Database URL programatically but it results to the following schema code

```prisma
datasource database {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = {"env":""}
}
```

leading to an error, attempted many different ways, by string and others but it doesn't work as planned

Following is my index.ts for the schemix

```ts
createSchema({
    basePath: __dirname,
    datasource: {
        provider: "postgresql",
        url: { env: "DATABASE_URL" },
        shadowDatabaseUrl: { env: "" }
    },
    generator: {
        provider: "prisma-client-js",
    },
}).export(__dirname, "schema");
```

For reproduction is just having the `shadowDatabaseUrl: { env: "" }` part in your index and it creates this scenario

Thanks in any advice I will try to fix this myself, if I figure out how to do without doing any kind of pull request will be great but If required I will create an pull request to this repo

**Comment by ridafkih** [comment]
Apologies for this bug, for the time being you can do `shadowDatabaseUrl: 'env("<NAME_HERE>")'`, but I will definitely get this fixed ASAP.

**Comment by ridafkih** [comment]
Added support in #57 !
