### ISSUE TITLE
Relation fields doesn't get generated when used as a mixin

### ISSUE THREAD

**Issue by Daidalos117** [ridafkih/schemix#33]
Hi,
when using .relation as this:
```
export default createMixin((UserRelationshipMixin) => {
  UserRelationshipMixin
    .relation("user", UserModel, {
      references: ["id"],
      fields: ["userId"],
    })
    .int("userId", { unique: true })
});
```
the resulting model is missing those fields. Please look into example:
https://codesandbox.io/s/exciting-leaf-bxqzvt?file=/src/models/Session.model.ts
As you can see, Token model has manually added those fields and everything is fine. Session model on the other hand is using mixin, and it lack those fields.

Thanks in advance :)

**Comment by ridafkih** [comment]
Thanks, will begin looking into this.

**Comment by ridafkih** [comment]
@Daidalos117 Went ahead and addressed the bug, thanks for the report! This will be out in the next release.

**Comment by Daidalos117** [comment]
Nice! Thank you! I wanted to fix it by myself, but it would probably took me forever 😄 Good job tho.
