### ISSUE TITLE
Mixins are not being added

### ISSUE THREAD

**Issue by efreila** [ridafkih/schemix#43]
Previously on `v1.6.1`, I was able to successfully use the `.mixin` method on a model and see my mixin properly being added.

After upgrading to the latest version (`v1.7.1`), it seems like `.mixin` isn't working anymore. I tried running the code from [this exact test case](https://github.com/ridafkih/schemix/blob/main/tests/modules/PrismaModel.spec.ts#L115-L128) and it seems to also not be working. The non-mixin fields get added, but the `id` from the mixin doesn't. When I ran the tests locally, Vitest tells me that the test case is obsolete.

**Comment by ridafkih** [comment]
Please review #44 for me, thanks so much once again!
