### ISSUE TITLE
1.7.1 re-orders fields

### ISSUE THREAD

**Issue by virbyte** [ridafkih/schemix#45]
from 1.7.0 to 1.7.1 a change was introduced so that fields in a model are re-ordered, I think many users (including me) have their fields in a particular order - is there any way to control the order like was the normal behaviour before 1.7.1?

The new order of fields seems pretty random indeed. My preference would be that they are as they are written (i.e. how it used to be). The current order is not even alphabetical... schemas are a mess now

**Comment by virbyte** [comment]
for now I'll just stick with 1.7.0 but it's a shame :)

**Comment by ridafkih** [comment]
@virbyte Thanks for the report.

Would the expected behaviour be alphabetical, or simply the way it is reflected within the source files. Personally I'd expect source files. 

Thanks for the report, will get on this tonight.

**Comment by virbyte** [comment]
default should definitely be same as source files, no question about it! things like prettier and linters can make schemas alphabetical, so that's not really a priority for schemix

**Comment by ridafkih** [comment]
This has been addressed in #49, fix will be released in v1.8.2 momentarily.

**Comment by ridafkih** [comment]
Annnddddd released! Fix is available in v1.8.2, thank you @FerasAloudah for your contribution and @virbyte for the report. Let me know if there are any more issues!

**Comment by FerasAloudah** [comment]
Great to hear! Thank you for your amazing work @ridafkih I've been using this for the past couple of days, and I'm really loving it. Currently refactoring our Prisma schema to use this, and everything is going on smoothly.
