### ISSUE TITLE
Support descriptions

### ISSUE THREAD

**Issue by overra** [ridafkih/schemix#55]
Schemix should support [providing descriptions](https://www.prisma.io/docs/concepts/components/prisma-schema#comments) for models and fields.

I haven't familiarized myself with the schemix source code yet, but I can give it try.

**Comment by ridafkih** [comment]
@overra Great idea!

**Comment by ridafkih** [comment]
@overra Getting to work on this. c:

**Comment by overra** [comment]
> @overra Getting to work on this. c:

Thank you! I don't have the time to get it done.

**Comment by ridafkih** [comment]
Added in #60 by @hedwiggggg!

**Comment by ridafkih** [comment]
Released in v1.11.0
